Initial commit for LPS code
pcdshub/lcls-plc-lps-02 pull request #1
Opened 2024-01-16 01:54 UTC by divyak1910

## Description

## Motivation and Context

## How Has This Been Tested?

## Where Has This Been Documented?

## Screenshots (if appropriate):

## Pre-merge checklist
- [ ] Code works interactively
- [ ] Code contains descriptive comments
- [ ] Test suite passes locally
- [ ] Libraries are set to fixed versions and not ``Always Newest``
- [ ] Code committed with ``pre-commit`` (alternatively ``pre-commit run --all-files``)

2024-01-16 01:57 UTC, divyak1910 commented
1. PLC code contains the same DUT, Programs as per Bay 3. 
2. Changes are made to GVL IO & linking
3. All beckhoff modules naming has been renamed as per standards and linking is based on EPLAN drawing

2024-04-18 18:09 UTC, slactjohnson commented
@divyak1910 Is this ready for review?

2024-05-09 00:45 UTC, divyak1910 commented
@slactjohnson : Hi Tyler, this is now ready for review. Recent commit has the latest Function block with the timer.

2024-05-10 20:45 UTC, slactjohnson requested changes
Hi Divya, I primarily reviewed the changes from the original commit to now, as the original code was nearly identical to the original system. I have a few questions about the timer implementation, but it looks functional. The code tab spacing looks a little funny, which I think is being caught by the CI tools. I think it would be good to resolve the failed CI checks if possible.

2024-05-10 20:45 UTC, slactjohnson commented on lcls-plc-lps-02/lcls_plc_lps_02/POUs/Devices/FB_Laser_Timer.TcPOU
> +            TimerOn := FALSE;  (* Reset timer status *)
It's not clear to me what TimerOn is used for; is this used somewhere else?

2024-05-10 20:45 UTC, slactjohnson commented on lcls-plc-lps-02/lcls_plc_lps_02/POUs/Devices/FB_Laser_Timer.TcPOU
> +            TimerOn := FALSE;  (* Reset timer status *)
If you want to keep this, you could potentially use TimerOn as the input to Timer, e.g.:
```
IF (error condition) THEN
    TimerOn := TRUE;
ELSE
    TimerOn := FALSE;
ENDIF
Timer(IN:=TimerOn);

IF Timer.Q THEN
....
```
and so on

2024-05-13 16:54 UTC, divyak1910 commented on lcls-plc-lps-02/lcls_plc_lps_02/POUs/Devices/FB_Laser_Timer.TcPOU
> +            TimerOn := FALSE;  (* Reset timer status *)
Hi @slactjohnson , I am using the TimerON to only show a status of the timer if it is ON/OFF. We can remove that. Its not used anywhere else. Please let me know if I need to remove it to avoid confusion. Thank you !

2024-05-13 22:22 UTC, slactjohnson commented on lcls-plc-lps-02/lcls_plc_lps_02/POUs/Devices/FB_Laser_Timer.TcPOU
> +            TimerOn := FALSE;  (* Reset timer status *)
@divyak1910 I think if it's not used anywhere, it may be confusing. I think it should be removed, or at least re-worked.

2024-05-14 20:31 UTC, divyak1910 commented
Hi @slactjohnson, I removed the TimerON function from the block. The pre-commit command was run again and committed. However, it is failing on the library version which is resolved on the code.

2024-05-14 22:22 UTC, slactjohnson commented
@divyak1910 Then we should move these libraries to fixed version

2024-05-15 22:44 UTC, divyak1910 commented
@slactjohnson : Hi Tyler, fixed the library versions. Thank you !

2024-05-20 15:54 UTC, slactjohnson approved these changes
LGTM

2024-05-21 18:11 UTC, merged